receivers:
  nop:

processors: 

exporters:
  nop:

service:
  pipelines:
    traces:
      receivers: [nop]
      processors: []
      exporters: [nop]
    metrics:
      receivers: [nop]
      processors: []
      exporters: [nop]
    logs:
      receivers: [nop]
      processors: []
      exporters: [nop]